### ISSUE TITLE
Error in annotate rest service

### ISSUE THREAD

**Issue by collarad** [dbpedia-spotlight/spotlight-docker#18]
Hello, after successfully starting the docker English container, I tried to call the annotate rest service but I got an internal error.

I started the service with the following command
docker run -i -e JAVA_OPTS='-Xmx16g' -p 2222:80 dbpedia/spotlight-english spotlight.sh

This is my rest request:
http://my_server:2222/rest/annotate?text=President Obama called Wednesday on Congress to extend a tax break for students included in last year's economic stimulus package, arguing that the policy provides more generous assistance&confidence=0.35

The error log message:

`Nov 16, 2017 4:59:00 PM com.sun.grizzly.http.servlet.ServletAdapter doService
SEVERE: service exception:
javax.servlet.ServletException: java.lang.NoClassDefFoundError: com/google/common/hash/Hashing
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.doFilter(ServletAdapter.java:1059)
        at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.invokeFilterChain(ServletAdapter.java:999)
        at com.sun.grizzly.http.servlet.ServletAdapter.doService(ServletAdapter.java:434)
        at com.sun.grizzly.http.servlet.ServletAdapter.service(ServletAdapter.java:379)
        at com.sun.grizzly.tcp.http11.GrizzlyAdapter.service(GrizzlyAdapter.java:179)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:849)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:746)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1045)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:228)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/google/common/hash/Hashing
        at org.nlp2rdf.bean.NIFBean.setReferenceContext(NIFBean.java:182)
        at org.nlp2rdf.bean.NIFBean.lambda$fillBeansWithContext$2(NIFBean.java:81)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.nlp2rdf.bean.NIFBean.fillBeansWithContext(NIFBean.java:81)
        at org.nlp2rdf.nif21.impl.NIF21.getModel(NIF21.java:45)
        at org.nlp2rdf.nif21.impl.NIF21.getTurtle(NIF21.java:80)
        at org.dbpedia.spotlight.web.rest.formats.NIFWrapper.process(NIFWrapper.java:138)
        at org.dbpedia.spotlight.web.rest.formats.NIFWrapper.getNIF(NIFWrapper.java:124)
        at org.dbpedia.spotlight.web.rest.OutputManager.makeNIF(OutputManager.java:118)
        at org.dbpedia.spotlight.web.rest.SpotlightInterface.getNIF(SpotlightInterface.java:287)
        at org.dbpedia.spotlight.web.rest.resources.Annotate.getNIF(Annotate.java:150)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        ... 22 more
`

**Comment by sandroacoelho** [comment]
Hi @collarad ,

Under api.dbpedia-spotlight.org we are using this image. Also I tried in my machine and works...
What is your docker version? I am using  version 1.12.6, build 78d1802 on Linux (Ubuntu and Debian)

Best,

![spot](https://user-images.githubusercontent.com/1160826/32909123-dfc3e058-caec-11e7-99c3-2aae8e0fab54.png)

**Comment by collarad** [comment]
Hello @sandroacoelho , thank you for the answer.

I pulled the tag **latest** from docker hub
And the docker version I am using is the same: version 1.12.6 build 78d182.

I will try creating the docker from scratch

**Comment by sandroacoelho** [comment]
Hi @collarad,

Due to no longer interaction, I am going to close this issue. If you need more help, just re-open it.

Best regards,

**Comment by agentydragon** [comment]
Hi! I have just encountered the same problem and I think I got it working now, so I wanted to leave some info here for posterity. I originally ran:

```
docker run -i -p 2222:80 dbpedia/spotlight-english spotlight.sh
```

And that resulted in the server logging this error:

```
SEVERE: The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NoClassDefFoundError: com/google/common/hash/Hashing
	at org.nlp2rdf.bean.NIFBean.setReferenceContext(NIFBean.java:182)
	at org.nlp2rdf.bean.NIFBean.lambda$fillBeansWithContext$2(NIFBean.java:81)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at org.nlp2rdf.bean.NIFBean.fillBeansWithContext(NIFBean.java:81)
	at org.nlp2rdf.nif21.impl.NIF21.getModel(NIF21.java:45)
	at org.nlp2rdf.nif21.impl.NIF21.getTurtle(NIF21.java:80)
	at org.dbpedia.spotlight.web.rest.formats.NIFWrapper.process(NIFWrapper.java:138)
	at org.dbpedia.spotlight.web.rest.formats.NIFWrapper.getNIF(NIFWrapper.java:124)
	at org.dbpedia.spotlight.web.rest.OutputManager.makeNIF(OutputManager.java:118)
	at org.dbpedia.spotlight.web.rest.SpotlightInterface.getNIF(SpotlightInterface.java:287)
	at org.dbpedia.spotlight.web.rest.resources.Annotate.getNIF(Annotate.java:150)
	at org.dbpedia.spotlight.web.rest.resources.Annotate.postNIF(Annotate.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.doFilter(ServletAdapter.java:1059)
	at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.invokeFilterChain(ServletAdapter.java:999)
	at com.sun.grizzly.http.servlet.ServletAdapter.doService(ServletAdapter.java:434)
	at com.sun.grizzly.http.servlet.ServletAdapter.service(ServletAdapter.java:379)
	at com.sun.grizzly.tcp.http11.GrizzlyAdapter.service(GrizzlyAdapter.java:179)
	at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:849)
	at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:746)
	at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1045)
	at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:228)
	at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
	at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
	at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
	at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
	at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.common.hash.Hashing
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

What helped for me was runnning:

```
docker run -i -e JAVA_OPTS='-Xmx10g' -p 2222:80 dbpedia/spotlight-english:latest spotlight.sh
```

I'm not sure if the thing that made it work was explicitly specifying the `latest` tag, or adding the `-Xmx10g`. The test command I used in both cases was:

```
curl http://localhost:2222/rest/annotate \                                                                                       20:37:31
  --data-urlencode "text=President Obama called Wednesday on Congress to extend a tax break
  for students included in last year's economic stimulus package, arguing
  that the policy provides more generous assistance." \
  --data "confidence=0.2" \
  --data "support=20"
```

**Comment by mlollo** [comment]
Hello! I encountered the same issue on the french version for the dbpedia/spotlight-french:latest (dbpedia-spotlight-nightly-build.jar) with this query :
```
curl http://localhost:2225/rest/annotate  --data-urlencode "text=Décédé le 3 juin dernier, Mohamed Ali est l'homme des superlatifs, celui qui aura marqué l'histoire de la boxe par ses combats épiques, ses multiples titres, son style, ses engagements politiques. Reconnu comme l'un des plus grands boxeurs de tous les temps, il se considérait lui-même comme le plus grand, le plus beau." --data "confidence=0.35"
```
How ever the dbpedia-spotlight-1.0.0.jar seems to work with the same query (dbpedia/spotlight-french:1.0)

Here the stack trace for dbpedia-spotlight-nightly-build.jar or dbpedia/spotlight-french:latest : 
```
SEVERE: The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NoClassDefFoundError: com/google/common/hash/Hashing
        at org.nlp2rdf.bean.NIFBean.setReferenceContext(NIFBean.java:182)
        at org.nlp2rdf.bean.NIFBean.lambda$fillBeansWithContext$2(NIFBean.java:81)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at org.nlp2rdf.bean.NIFBean.fillBeansWithContext(NIFBean.java:81)
        at org.nlp2rdf.nif21.impl.NIF21.getModel(NIF21.java:45)
        at org.nlp2rdf.nif21.impl.NIF21.getTurtle(NIF21.java:80)
        at org.dbpedia.spotlight.web.rest.formats.NIFWrapper.process(NIFWrapper.java:138)
        at org.dbpedia.spotlight.web.rest.formats.NIFWrapper.getNIF(NIFWrapper.java:124)
        at org.dbpedia.spotlight.web.rest.OutputManager.makeNIF(OutputManager.java:118)
        at org.dbpedia.spotlight.web.rest.SpotlightInterface.getNIF(SpotlightInterface.java:287)
        at org.dbpedia.spotlight.web.rest.resources.Annotate.getNIF(Annotate.java:150)
        at org.dbpedia.spotlight.web.rest.resources.Annotate.postNIF(Annotate.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.doFilter(ServletAdapter.java:1059)
        at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.invokeFilterChain(ServletAdapter.java:999)
        at com.sun.grizzly.http.servlet.ServletAdapter.doService(ServletAdapter.java:434)
        at com.sun.grizzly.http.servlet.ServletAdapter.service(ServletAdapter.java:379)
        at com.sun.grizzly.tcp.http11.GrizzlyAdapter.service(GrizzlyAdapter.java:179)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:849)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:746)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1045)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:228)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.common.hash.Hashing
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 50 more

Jan 29, 2019 3:28:11 PM com.sun.grizzly.http.servlet.ServletAdapter doService
SEVERE: service exception:
javax.servlet.ServletException: java.lang.NoClassDefFoundError: com/google/common/hash/Hashing
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.doFilter(ServletAdapter.java:1059)
        at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.invokeFilterChain(ServletAdapter.java:999)
        at com.sun.grizzly.http.servlet.ServletAdapter.doService(ServletAdapter.java:434)
        at com.sun.grizzly.http.servlet.ServletAdapter.service(ServletAdapter.java:379)
        at com.sun.grizzly.tcp.http11.GrizzlyAdapter.service(GrizzlyAdapter.java:179)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:849)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:746)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1045)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:228)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/google/common/hash/Hashing
        at org.nlp2rdf.bean.NIFBean.setReferenceContext(NIFBean.java:182)
        at org.nlp2rdf.bean.NIFBean.lambda$fillBeansWithContext$2(NIFBean.java:81)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at org.nlp2rdf.bean.NIFBean.fillBeansWithContext(NIFBean.java:81)
        at org.nlp2rdf.nif21.impl.NIF21.getModel(NIF21.java:45)
        at org.nlp2rdf.nif21.impl.NIF21.getTurtle(NIF21.java:80)
        at org.dbpedia.spotlight.web.rest.formats.NIFWrapper.process(NIFWrapper.java:138)
        at org.dbpedia.spotlight.web.rest.formats.NIFWrapper.getNIF(NIFWrapper.java:124)
        at org.dbpedia.spotlight.web.rest.OutputManager.makeNIF(OutputManager.java:118)
        at org.dbpedia.spotlight.web.rest.SpotlightInterface.getNIF(SpotlightInterface.java:287)
        at org.dbpedia.spotlight.web.rest.resources.Annotate.getNIF(Annotate.java:150)
        at org.dbpedia.spotlight.web.rest.resources.Annotate.postNIF(Annotate.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: com.google.common.hash.Hashing
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 50 more
```

**Comment by syats** [comment]
I confirm that the same error can be fixed in the german version using:

`docker run --rm --name spotlight -e JAVA_OPTS='-Xmx8g'  -i -p 2226:80 dbpedia/spotlight-german:latest spotlight.sh`
