### ISSUE TITLE
Loading MemorySurfaceFormStore... Killed

### ISSUE THREAD

**Issue by dpicca** [dbpedia-spotlight/spotlight-docker#39]
Hi
I am trying to install the spotlight-dbpedia docker as described here:
https://github.com/dbpedia-spotlight/spotlight-docker/tree/master/v1.0/english

So when I run the command:
docker run -itd --restart unless-stopped --name spotlight_en -p 2222:80 english_spotlight spotlight.sh

the process keeps to end up killed. This is the log:

`574 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryQuantizedCountStore...
643 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (68 ms)
644 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryTokenTypeStore...
5824 [main] INFO org.dbpedia.spotlight.db.memory.MemoryTokenTypeStore - Creating reverse-lookup for Tokens.
8747 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (8101 ms)
8748 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemorySurfaceFormStore...
Killed
902 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryQuantizedCountStore...
980 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (76 ms)
983 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryTokenTypeStore...
5245 [main] INFO org.dbpedia.spotlight.db.memory.MemoryTokenTypeStore - Creating reverse-lookup for Tokens.
7604 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (6620 ms)
7606 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemorySurfaceFormStore...
Killed
....`

I also tried to run it without docker using this procedure:

`
wget https://sourceforge.net/projects/dbpedia-spotlight/files/spotlight/dbpedia-spotlight-1.0.0.jar
wget -O en.tar.gz http://downloads.dbpedia.org/repo/dbpedia/spotlight/spotlight-model/2020.11.18/spotlight-model_lang%3den.tar.gz
tar xzf en.tar.gz
java -jar dbpedia-spotlight-1.0.0.jar en http://localhost:2222/rest`

and this is what i get in return:

`361 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryQuantizedCountStore...
413 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (52 ms)
414 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryTokenTypeStore...
3000 [main] INFO org.dbpedia.spotlight.db.memory.MemoryTokenTypeStore - Creating reverse-lookup for Tokens.
4136 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (3722 ms)
4137 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemorySurfaceFormStore...
Exception in thread "main" com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
stringForID (org.dbpedia.spotlight.db.memory.MemorySurfaceFormStore)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:162)
	at com.esotericsoftware.kryo.io.Input.readAscii_slow(Input.java:551)
	at com.esotericsoftware.kryo.io.Input.readAscii(Input.java:529)
	at com.esotericsoftware.kryo.io.Input.readString(Input.java:407)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$StringArraySerializer.read(DefaultArraySerializers.java:282)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$StringArraySerializer.read(DefaultArraySerializers.java:262)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:702)
	at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:611)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:732)
	at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:166)
	at org.dbpedia.spotlight.db.memory.MemoryStore$.loadSurfaceFormStore(MemoryStore.scala:181)
	at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:54)
	at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:80)
	at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
	at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:229)
	at org.dbpedia.spotlight.web.rest.Server.main(Server.java:87)`

I initially thought it was a RAM memory issue so I tried to increase it via '-Xmx16g' parameter  as suggested here https://github.com/dbpedia-spotlight/spotlight-docker/issues/17#issuecomment-344993328
but it does not solve the problem

Any help please?

Many thanks

Dave

**Comment by dpicca** [comment]
Solved.. increase memory through Docker app https://stackoverflow.com/questions/43170089/docker-wont-start-on-windows-not-enough-memory-to-start-docker
